spring:
  datasource:
    url: jdbc:mysql://calories-calculator.cezbobkqi7q6.eu-central-1.rds.amazonaws.com:3306/calories-calculator
    username: fenix
    password: atybrclbvf

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate.format_sql: true
    hibernate:
      ddl-auto: update

server:
  port: 5000

spring.mvc.hiddenmethod.filter.enabled: true